stages:
  - build

build-package:
  stage: build
  only:
    - tags
  image: python:3.9 
  script:
    - python3 -m pip install --upgrade build
    - python3 -m build
  artifacts:
    paths:
      - dist/