[build-system]
requires = ["setuptools>61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dicomorganizer"
version = "0.4.4" 
description = "A package to manage, process, and anonymize DICOM files."
readme = "README.md"
authors = [{name = "Kobe Bamps", email = "kobe.bamps@uzleuven.be"}]
license = {text = "MIT"}  # Adjust to match your actual license
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/kbamps/dicomorganizer"

[tool.setuptools.packages]
find = {where = ["dicomorganizer"]}